project:
    project-id: 
    region: us-central1
    zone: us-central1-a

bucket:
    bucket-name: 

instance:
    instance-prefix-name: montatiles-
    machine-type: n2-standard-4
    startup-script: startup-script.sh

disks:
    snapshot-name: teste
